#include "urldelegate.h"

UrlDelegate::UrlDelegate(QObject * parent):QAbstractItemDelegate(parent)
{
    buildKwordLinks();
}



void UrlDelegate::paint(QPainter *painter, const QStyleOptionViewItem &option,const QModelIndex &index) const
{

/*
    QString text = index.data(Qt::DisplayRole).toString();
    if (text.isEmpty())
        return;
*/

    painter->save();
    if (option.state & QStyle::State_MouseOver)
    {
        QFont font = option.font;
        font.setUnderline(true);
        painter->setFont(font);
        painter->setPen(option.palette.link().color());
    }
    painter->drawText(option.rect, Qt::AlignLeft | Qt::AlignVCenter,index.data(Qt::DisplayRole).toString());

    painter->restore();
}


QSize UrlDelegate::sizeHint(const QStyleOptionViewItem &option,
                             const QModelIndex &index) const
{
    return QSize(20, 20);//QAbstractItemDelegate::sizeHint(option, index);
}


bool UrlDelegate::editorEvent(QEvent *event, QAbstractItemModel *model,
                              const QStyleOptionViewItem &option, const QModelIndex &index)
{

    if (event->type()==QEvent::MouseButtonDblClick){
        QString HesselTerm= index.data(Qt::DisplayRole).toString();
        int htmlIndex=listKwords.indexOf(HesselTerm);
        if (htmlIndex==-1)
        {
            QMessageBox messageBox;
            messageBox.critical(0,tr("Error"),tr("Término exacto no encontrado"));
            messageBox.setFixedSize(500,200);
            return true;
        }
        else
        {
            QDesktopServices::openUrl(QUrl(listLinks.at(htmlIndex), QUrl::TolerantMode));
        }
        return true;
    }
    return false;
}

void UrlDelegate::buildKwordLinks()
{
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/introduction.html"));
    listKwords.append(QString("Introduction"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/name.html"));
    listKwords.append(QString("name"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/irest.html"));
    listKwords.append(QString("irest"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/nohydro.html"));
    listKwords.append(QString("nohydro"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/itype.html"));
    listKwords.append(QString("itype"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/lwall.html"));
    listKwords.append(QString("lwall"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/lpr.html"));
    listKwords.append(QString("lpr"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/irez.html"));
    listKwords.append(QString("irez"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/ncfilm.html"));
    listKwords.append(QString("ncfilm"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/nctap8.html"));
    listKwords.append(QString("nctap8"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/nclast.html"));
    listKwords.append(QString("nclast"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/ncmon.html"));
    listKwords.append(QString("ncmon"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/ncaspec.html"));
    listKwords.append(QString("ncaspec"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/gmv.html"));
    listKwords.append(QString("gmv"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/cafilm.html"));
    listKwords.append(QString("cafilm"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/cafin.html"));
    listKwords.append(QString("cafin"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/angmom.html"));
    listKwords.append(QString("angmom"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/pgssw.html"));
    listKwords.append(QString("pgssw"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/dti.html"));
    listKwords.append(QString("dti"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/dtmxca.html"));
    listKwords.append(QString("dtmxca"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/dtmax.html"));
    listKwords.append(QString("dtmax"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/tlimd.html"));
    listKwords.append(QString("tlimd"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/twfilm.html"));
    listKwords.append(QString("twfilm"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/twfin.html"));
    listKwords.append(QString("twfin"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/fchsp.html"));
    listKwords.append(QString("fchsp"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/bore.html"));
    listKwords.append(QString("bore"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/stroke.html"));
    listKwords.append(QString("stroke"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/squish.html"));
    listKwords.append(QString("squish"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/rpm.html"));
    listKwords.append(QString("rpm"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/atdc.html"));
    listKwords.append(QString("atdc"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/datdct.html"));
    listKwords.append(QString("datdct"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/revrep.html"));
    listKwords.append(QString("revrep"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/conrod.html"));
    listKwords.append(QString("conrod"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/swirl.html"));
    listKwords.append(QString("swirl"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/swipro.html"));
    listKwords.append(QString("swipro"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/thsect.html"));
    listKwords.append(QString("thsect"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/sector.html"));
    listKwords.append(QString("sector"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/deact.html"));
    listKwords.append(QString("deact"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/epsy.html"));
    listKwords.append(QString("epsy"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/epsv.html"));
    listKwords.append(QString("epsv"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/epsp.html"));
    listKwords.append(QString("epsp"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/epst.html"));
    listKwords.append(QString("epst"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/epsk.html"));
    listKwords.append(QString("epsk"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/epse.html"));
    listKwords.append(QString("epse"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/gx.html"));
    listKwords.append(QString("gx"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/gy.html"));
    listKwords.append(QString("gy"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/gz.html"));
    listKwords.append(QString("gz"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/tcylwl.html"));
    listKwords.append(QString("tcylwl"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/thead.html"));
    listKwords.append(QString("thead"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/tpistn.html"));
    listKwords.append(QString("tpistn"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/pardon.html"));
    listKwords.append(QString("pardon"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/a0b0.html"));
    listKwords.append(QString("a0"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/a0b0.html"));
    listKwords.append(QString("b0"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/artvis.html"));
    listKwords.append(QString("artvis"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/ecnsrv.html"));
    listKwords.append(QString("ecnsrv"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/adia.html"));
    listKwords.append(QString("adia"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/anu0.html"));
    listKwords.append(QString("anu0"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/visrat.html"));
    listKwords.append(QString("visrat"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/tcut.html"));
    listKwords.append(QString("tcut"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/tcute.html"));
    listKwords.append(QString("tcute"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/epschm.html"));
    listKwords.append(QString("epschm"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/omgchm.html"));
    listKwords.append(QString("omgchm"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/turbsw.html"));
    listKwords.append(QString("turbsw"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/sgsl.html"));
    listKwords.append(QString("sgsl"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/trbchem.html"));
    listKwords.append(QString("trbchem"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/capa.html"));
    listKwords.append(QString("capa"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/pmplict.html"));
    listKwords.append(QString("pmplict"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/lospeed.html"));
    listKwords.append(QString("lospeed"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/airmu1airmu2.html"));
    listKwords.append(QString("airmu1"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/airmu1airmu2.html"));
    listKwords.append(QString("airmu2"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/airla1airla2.html"));
    listKwords.append(QString("airla1"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/airla1airla2.html"));
    listKwords.append(QString("airla2"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/prl.html"));
    listKwords.append(QString("prl"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/rpr.html"));
    listKwords.append(QString("rpr"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/rsc.html"));
    listKwords.append(QString("rsc"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/xignit.html"));
    listKwords.append(QString("xignit"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/t1ign.html"));
    listKwords.append(QString("t1ign"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/tdign.html"));
    listKwords.append(QString("tdign"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/ca1ign.html"));
    listKwords.append(QString("ca1ign"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/cadign.html"));
    listKwords.append(QString("cadign"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/xignl1zignt1.html"));
    listKwords.append(QString("xignl1"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/xignl1zignt1.html"));
    listKwords.append(QString("zignt1"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/xignl2zignt2.html"));
    listKwords.append(QString("xignl2"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/xignl2zignt2.html"));
    listKwords.append(QString("zignt2"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/kwikeq.html"));
    listKwords.append(QString("kwikeq"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/numnoz.html"));
    listKwords.append(QString("numnoz"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/numinj.html"));
    listKwords.append(QString("numinj"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/numvel.html"));
    listKwords.append(QString("numvel"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/t1inj.html"));
    listKwords.append(QString("t1inj"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/tdinj.html"));
    listKwords.append(QString("tdinj"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/ca1inj.html"));
    listKwords.append(QString("ca1inj"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/cadinj.html"));
    listKwords.append(QString("cadinj"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/tspmas.html"));
    listKwords.append(QString("tspmas"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/tnparc.html"));
    listKwords.append(QString("tnparc"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/pulse.html"));
    listKwords.append(QString("pulse"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/injdist.html"));
    listKwords.append(QString("injdist"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/kolide.html"));
    listKwords.append(QString("kolide"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/tpi.html"));
    listKwords.append(QString("tpi"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/turb.html"));
    listKwords.append(QString("turb"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/breakup.html"));
    listKwords.append(QString("breakup"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/evapp.html"));
    listKwords.append(QString("evapp"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/numdiv.html"));
    listKwords.append(QString("numdiv"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/scf.html"));
    listKwords.append(QString("scf"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/drnoz.html"));
    listKwords.append(QString("drnoz"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/dznoz.html"));
    listKwords.append(QString("dznoz"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/dthnoz.html"));
    listKwords.append(QString("dthnoz"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/tiltxy.html"));
    listKwords.append(QString("tiltxy"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/tiltxz.html"));
    listKwords.append(QString("tiltxz"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/cone.html"));
    listKwords.append(QString("cone"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/dcone.html"));
    listKwords.append(QString("dcone"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/anoz.html"));
    listKwords.append(QString("anoz"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/smr.html"));
    listKwords.append(QString("smr"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/amp0.html"));
    listKwords.append(QString("amp0"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/diameterinjector.html"));
    listKwords.append(QString("diameterinjector"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/velinj.html"));
    listKwords.append(QString("velinj"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/nsp.html"));
    listKwords.append(QString("nsp"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/datahk.html"));
    listKwords.append(QString("datahk(isaninputfile)"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/idspFuelSpecies.html"));
    listKwords.append(QString("idsp(fuelspecies)"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/ylminitial.html"));
    listKwords.append(QString("ylminitial"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/diffusionl.html"));
    listKwords.append(QString("diffusionl"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/idspNonFuelSpecies.html"));
    listKwords.append(QString("idsp(non-fuelspecies)"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/mw.html"));
    listKwords.append(QString("mw"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/htform.html"));
    listKwords.append(QString("htform"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/stoifuel.html"));
    listKwords.append(QString("stoifuel"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/stoifuel.html"));
    listKwords.append(QString("stoio2"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/nregions.html"));
    listKwords.append(QString("nregions"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/presi.html"));
    listKwords.append(QString("presi"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/tempi.html"));
    listKwords.append(QString("tempi"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/tkei.html"));
    listKwords.append(QString("tkei"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/scli.html"));
    listKwords.append(QString("scli"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/er.html"));
    listKwords.append(QString("er"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/mfrac.html"));
    listKwords.append(QString("mfrac"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/nrk.html"));
    listKwords.append(QString("nrk"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/cfEfZetaf.html"));
    listKwords.append(QString("cf"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/cfEfZetaf.html"));
    listKwords.append(QString("ef"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/cfEfZetaf.html"));
    listKwords.append(QString("zetaf"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/cbEbZetab.html"));
    listKwords.append(QString("cb"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/cbEbZetab.html"));
    listKwords.append(QString("eb"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/cbEbZetab.html"));
    listKwords.append(QString("zetab"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/am.html"));
    listKwords.append(QString("am"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/bm.html"));
    listKwords.append(QString("bm"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/ae.html"));
    listKwords.append(QString("ae"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/be.html"));
    listKwords.append(QString("be"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/nre.html"));
    listKwords.append(QString("nre"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/asThroughEs.html"));
    listKwords.append(QString("asthroughes"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/an.html"));
    listKwords.append(QString("an"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/bn.html"));
    listKwords.append(QString("bn"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/nvalves.html"));
    listKwords.append(QString("nvalves"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/vliftmin.html"));
    listKwords.append(QString("vliftmin"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/skirtth.html"));
    listKwords.append(QString("skirtth"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/tmove.html"));
    listKwords.append(QString("tmove"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/vtiltxz.html"));
    listKwords.append(QString("vtiltxz"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/nlift.html"));
    listKwords.append(QString("nlift"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/isoot.html"));
    listKwords.append(QString("isoot"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/distamb.html"));
    listKwords.append(QString("distamb"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/pamb.html"));
    listKwords.append(QString("pamb"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/tkeamb.html"));
    listKwords.append(QString("tkeamb"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/sclamb.html"));
    listKwords.append(QString("sclamb"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/velin.html"));
    listKwords.append(QString("velin"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/reedin.html"));
    listKwords.append(QString("reedin"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/reedout.html"));
    listKwords.append(QString("reedout"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/nregin0.html"));
    listKwords.append(QString("nregin0"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/nregamb.html"));
    listKwords.append(QString("nregamb"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/numpcc.html"));
    listKwords.append(QString("numpcc"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/numpcc.html"));
    listKwords.append(QString("capcc"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/numpcc.html"));
    listKwords.append(QString("pcc"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/numpex.html"));
    listKwords.append(QString("numpex"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/numpex.html"));
    listKwords.append(QString("capex"));
    listLinks.append(QString("http://homepages.cae.wisc.edu/%7Ehessel/manualsAndEpilogues/kiva4itape5inputs/numpex.html"));
    listKwords.append(QString("pex"));
}

